import { useEffect, useMemo, useState } from "react";
import { apiFetch } from "../../config/api";
import PageMeta from "../../components/common/PageMeta";
import AdminManagement from "./AdminManagement";

type MonthlyPoint = { key: string; label: string; billed: number; collected: number; patientPayments: number; insurancePayments: number };
type ExecutiveDashboard = {
  generatedAt: string;
  disclaimer: string;
  overview: { activePatients: number; newPatientsToday: number; consultationsToday: number; activeHospitalizations: number; freeBeds: number; totalBeds: number };
  financial: { billedMonth: number; collectedMonth: number; receivables: number; patientPaymentsMonth: number; insurancePaymentsMonth: number; insuranceOutstanding: number; payrollMonth: number; monthly: MonthlyPoint[] };
  performance: { services: Array<{ name: string; patients: number; staff: number }>; roles: Array<{ role: string; count: number }> };
  alerts: Array<{ level: string; category: string; message: string }>;
  reports: { invoicesInPeriod: number; paymentsInPeriod: number; claimsPending: number; activeStaff: number };
};

const tabs = ["Vue globale", "Finances", "Performances", "Alertes & rapports", "Administrateurs"] as const;
type Tab = (typeof tabs)[number];
const cdf = (value: number) => `${Number(value || 0).toLocaleString("fr-FR")} CDF`;
const roleLabel: Record<string, string> = { ADMIN: "Administrateurs", PHYSICIAN: "Médecins", NURSE: "Infirmiers", PHARMACIST: "Pharmaciens", RECEPTIONIST: "Réception", CASHIER: "Caisse", FINANCE: "Finance", RADIOLOGIST: "Radiologie", LAB_MANAGER: "Responsables labo", LAB_TECHNICIAN: "Techniciens labo" };

export default function DashboardSupAdmin() {
  const [tab, setTab] = useState<Tab>(tabs[0]);
  const [data, setData] = useState<ExecutiveDashboard | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const load = async () => {
    setLoading(true); setError(null);
    try { setData(await apiFetch<ExecutiveDashboard>("/administration/executive-dashboard")); }
    catch (reason) { setError(reason instanceof Error ? reason.message : "La synthèse directionnelle n’a pas pu être chargée."); }
    finally { setLoading(false); }
  };
  useEffect(() => {
    void load(); const refresh = () => void load();
    window.addEventListener("aulia:realtime.update", refresh); window.addEventListener("aulia:billing.updated", refresh);
    return () => { window.removeEventListener("aulia:realtime.update", refresh); window.removeEventListener("aulia:billing.updated", refresh); };
  }, []);
  const largestService = useMemo(() => [...(data?.performance.services || [])].sort((a, b) => b.patients - a.patients)[0], [data]);
  return <div className="mx-auto w-full max-w-7xl space-y-5 px-4 py-4 sm:px-6 sm:py-6 lg:px-8">
    <PageMeta title="Direction générale | Aulia Care" description="Pilotage consolidé de l’établissement." />
    <section className="aulia-card overflow-hidden p-5 sm:p-7"><div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-aulia-teal">Direction générale</p><h1 className="mt-2 text-2xl font-semibold text-aulia-navy dark:text-white sm:text-3xl">Vue complète de l’établissement</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600 dark:text-slate-300">Activité, encaissements, créances, capacité, ressources et alertes prioritaires, en langage clair.</p></div><button type="button" onClick={() => void load()} disabled={loading} className="rounded-xl border border-aulia-teal/30 px-4 py-2.5 text-sm font-semibold text-aulia-teal transition hover:bg-aulia-mist disabled:opacity-50 dark:hover:bg-aulia-teal/10">Actualiser les données</button></div><div className="mt-6 flex gap-2 overflow-x-auto pb-1">{tabs.map((item) => <button key={item} type="button" onClick={() => setTab(item)} className={`whitespace-nowrap rounded-xl px-4 py-2.5 text-sm font-semibold transition ${tab === item ? "bg-aulia-teal text-white shadow-sm" : "border border-slate-200 text-slate-600 hover:bg-aulia-mist dark:border-slate-700 dark:text-slate-300 dark:hover:bg-slate-800"}`}>{item}</button>)}</div></section>
    {tab !== "Administrateurs" && loading && <section className="aulia-card p-8 text-center text-sm text-slate-500 dark:text-slate-300">Chargement de la synthèse directionnelle…</section>}
    {tab !== "Administrateurs" && error && <section className="rounded-2xl border border-red-200 bg-red-50 p-5 text-sm text-red-800 dark:border-red-900/50 dark:bg-red-950/30 dark:text-red-200"><p className="font-semibold">Synthèse indisponible</p><p className="mt-1">{error}</p><button type="button" onClick={() => void load()} className="mt-3 rounded-lg bg-red-700 px-3 py-2 font-semibold text-white">Réessayer</button></section>}
    {tab === "Administrateurs" && <AdminManagement />}
    {!loading && data && tab !== "Administrateurs" && <><div>{tab === "Vue globale" && <Overview data={data} largestService={largestService} />}{tab === "Finances" && <Finance data={data} />}{tab === "Performances" && <Performance data={data} />}{tab === "Alertes & rapports" && <AlertsAndReports data={data} />}</div><p className="px-1 text-xs leading-5 text-slate-500 dark:text-slate-400">Mis à jour le {new Intl.DateTimeFormat("fr-FR", { dateStyle: "medium", timeStyle: "short" }).format(new Date(data.generatedAt))}. {data.disclaimer}</p></>}
  </div>;
}

function Overview({ data, largestService }: { data: ExecutiveDashboard; largestService?: { name: string; patients: number } }) { return <div className="space-y-5"><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Kpi label="Patients suivis" value={data.overview.activePatients} detail="Dossiers actifs" /><Kpi label="Nouvelles admissions" value={data.overview.newPatientsToday} detail="Enregistrées aujourd’hui" /><Kpi label="Consultations du jour" value={data.overview.consultationsToday} detail="Activité clinique créée aujourd’hui" /><Kpi label="Hospitalisations en cours" value={data.overview.activeHospitalizations} detail={`${data.overview.freeBeds} lit(s) libre(s) sur ${data.overview.totalBeds}`} tone="teal" /></section><section className="grid gap-4 lg:grid-cols-2"><article className="aulia-card p-5 sm:p-6"><p className="text-xs font-bold uppercase tracking-[.14em] text-aulia-teal">Lecture rapide</p><h2 className="mt-2 text-lg font-semibold text-aulia-navy dark:text-white">Ce qu’il faut retenir aujourd’hui</h2><dl className="mt-5 space-y-3 text-sm"><Insight label="Encaissements du mois" value={cdf(data.financial.collectedMonth)} /><Insight label="Montant à recouvrer" value={cdf(data.financial.receivables)} alert={data.financial.receivables > 0} /><Insight label="Pôle le plus suivi" value={largestService ? `${largestService.name} · ${largestService.patients} patient(s)` : "Aucune activité ventilée"} /></dl></article><article className="aulia-card p-5 sm:p-6"><p className="text-xs font-bold uppercase tracking-[.14em] text-aulia-teal">Capacité de soins</p><h2 className="mt-2 text-lg font-semibold text-aulia-navy dark:text-white">Lits et continuité opérationnelle</h2><div className="mt-6 rounded-2xl bg-aulia-mist p-5 dark:bg-aulia-teal/10"><p className="text-4xl font-semibold text-aulia-navy dark:text-white">{data.overview.freeBeds}<span className="text-base font-medium text-slate-500 dark:text-slate-300"> / {data.overview.totalBeds}</span></p><p className="mt-2 text-sm text-slate-600 dark:text-slate-300">lits immédiatement disponibles. Vérifiez les alertes si la capacité devient nulle.</p></div></article></section></div>; }
function Finance({ data }: { data: ExecutiveDashboard }) { const max = Math.max(1, ...data.financial.monthly.flatMap((item) => [item.billed, item.collected])); return <div className="space-y-5"><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Kpi label="Facturé ce mois" value={cdf(data.financial.billedMonth)} detail="Factures émises" /><Kpi label="Réellement encaissé" value={cdf(data.financial.collectedMonth)} detail="Paiements enregistrés" tone="teal" /><Kpi label="Créances à recouvrer" value={cdf(data.financial.receivables)} detail="Solde des factures" tone="amber" /><Kpi label="Assurances en attente" value={cdf(data.financial.insuranceOutstanding)} detail="Demandes non finalisées" tone="red" /></section><section className="grid gap-5 xl:grid-cols-[minmax(0,1.6fr)_minmax(280px,1fr)]"><article className="aulia-card overflow-x-auto p-5 sm:p-6"><h2 className="text-lg font-semibold text-aulia-navy dark:text-white">Facturation et encaissements sur 12 mois</h2><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">Bleu : facturé. Vert : encaissé. Une facture n’est pas automatiquement un paiement.</p><div className="mt-6 flex h-56 min-w-[560px] items-end gap-2">{data.financial.monthly.map((item) => <div key={item.key} className="flex h-full min-w-[38px] flex-1 flex-col justify-end gap-1 text-center"><div title={`Facturé : ${cdf(item.billed)}`} style={{ height: `${Math.max(2, item.billed / max * 100)}%` }} className="rounded-t-md bg-aulia-navy/85" /><div title={`Encaissé : ${cdf(item.collected)}`} style={{ height: `${Math.max(2, item.collected / max * 100)}%` }} className="rounded-t-md bg-aulia-teal" /><span className="mt-1 text-[10px] text-slate-500">{item.label}</span></div>)}</div><div className="mt-3 flex gap-5 text-xs text-slate-500"><span>● Bleu : facturé</span><span className="text-aulia-teal">● Vert : encaissé</span></div></article><article className="aulia-card p-5 sm:p-6"><h2 className="text-lg font-semibold text-aulia-navy dark:text-white">Origine des paiements — ce mois</h2><div className="mt-6 space-y-5"><PaymentShare label="Patients / entreprises" value={data.financial.patientPaymentsMonth} total={data.financial.collectedMonth} /><PaymentShare label="Assurances" value={data.financial.insurancePaymentsMonth} total={data.financial.collectedMonth} /><Insight label="Paie traitée ce mois" value={cdf(data.financial.payrollMonth)} /></div></article></section></div>; }
function Performance({ data }: { data: ExecutiveDashboard }) { return <div className="grid gap-5 xl:grid-cols-2"><article className="aulia-card overflow-hidden"><div className="border-b border-slate-200 p-5 dark:border-slate-800"><h2 className="font-semibold text-aulia-navy dark:text-white">Activité par pôle</h2><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">Patients rattachés et effectif actif.</p></div><DataTable headers={["Service", "Patients", "Équipe"]} rows={data.performance.services.map((item) => [item.name, item.patients, item.staff])} empty="Aucun service actif." /></article><article className="aulia-card overflow-hidden"><div className="border-b border-slate-200 p-5 dark:border-slate-800"><h2 className="font-semibold text-aulia-navy dark:text-white">Effectif actif par fonction</h2></div><DataTable headers={["Fonction", "Nombre"]} rows={data.performance.roles.map((item) => [roleLabel[item.role] || item.role, item.count])} empty="Aucun effectif actif." /></article></div>; }
function AlertsAndReports({ data }: { data: ExecutiveDashboard }) { return <div className="grid gap-5 xl:grid-cols-[minmax(0,1.4fr)_minmax(280px,1fr)]"><article className="aulia-card overflow-hidden"><div className="border-b border-slate-200 p-5 dark:border-slate-800"><h2 className="font-semibold text-aulia-navy dark:text-white">Alertes nécessitant votre attention</h2><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">Une alerte signale un risque opérationnel et demande validation humaine.</p></div><div className="space-y-3 p-5">{data.alerts.length ? data.alerts.map((alert, index) => <div key={`${alert.category}-${index}`} className="rounded-xl border border-amber-200 bg-amber-50 p-4 dark:border-amber-500/20 dark:bg-amber-500/10"><p className="text-xs font-bold uppercase tracking-wide text-amber-800 dark:text-amber-300">{alert.level} · {alert.category}</p><p className="mt-1 text-sm font-medium text-slate-800 dark:text-slate-100">{alert.message}</p></div>) : <p className="rounded-xl bg-aulia-mist p-4 text-sm text-aulia-navy dark:bg-aulia-teal/10 dark:text-aulia-mist">Aucune alerte prioritaire issue des données disponibles.</p>}</div></article><article className="aulia-card p-5 sm:p-6"><h2 className="font-semibold text-aulia-navy dark:text-white">Base des rapports</h2><dl className="mt-5 space-y-4"><Insight label="Factures analysées (12 mois)" value={data.reports.invoicesInPeriod} /><Insight label="Paiements analysés (12 mois)" value={data.reports.paymentsInPeriod} /><Insight label="Dossiers assurance en attente" value={data.reports.claimsPending} alert={data.reports.claimsPending > 0} /><Insight label="Personnel actif" value={data.reports.activeStaff} /></dl></article></div>; }
function Kpi({ label, value, detail, tone = "navy" }: { label: string; value: number | string; detail: string; tone?: "navy" | "teal" | "amber" | "red" }) { const color = { navy: "text-aulia-navy dark:text-white", teal: "text-aulia-teal dark:text-aulia-mist", amber: "text-amber-700 dark:text-amber-300", red: "text-red-700 dark:text-red-300" }[tone]; return <article className="aulia-card p-5"><p className="text-sm text-slate-500 dark:text-slate-400">{label}</p><p className={`mt-2 text-2xl font-semibold ${color}`}>{value}</p><p className="mt-2 text-xs leading-5 text-slate-500 dark:text-slate-400">{detail}</p></article>; }
function Insight({ label, value, alert = false }: { label: string; value: number | string; alert?: boolean }) { return <div className="flex items-start justify-between gap-4 border-b border-slate-100 pb-3 last:border-0 last:pb-0 dark:border-slate-800"><dt className="text-slate-600 dark:text-slate-300">{label}</dt><dd className={`text-right font-semibold ${alert ? "text-amber-700 dark:text-amber-300" : "text-aulia-navy dark:text-white"}`}>{value}</dd></div>; }
function PaymentShare({ label, value, total }: { label: string; value: number; total: number }) { const percent = total > 0 ? Math.round(value / total * 100) : 0; return <div><div className="flex justify-between gap-3 text-sm"><span className="text-slate-600 dark:text-slate-300">{label}</span><span className="font-semibold text-aulia-navy dark:text-white">{cdf(value)} · {percent}%</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-100 dark:bg-slate-800"><div style={{ width: `${percent}%` }} className="h-full rounded-full bg-aulia-teal" /></div></div>; }
function DataTable({ headers, rows, empty }: { headers: string[]; rows: Array<Array<string | number>>; empty: string }) { return <div className="overflow-x-auto"><table className="min-w-[420px] w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500 dark:bg-slate-950 dark:text-slate-400"><tr>{headers.map((header) => <th key={header} className="px-5 py-3 font-semibold">{header}</th>)}</tr></thead><tbody>{rows.length ? rows.map((row, index) => <tr key={index} className="border-t border-slate-100 dark:border-slate-800">{row.map((value, cell) => <td key={cell} className="px-5 py-3.5 text-slate-700 dark:text-slate-200">{value}</td>)}</tr>) : <tr><td colSpan={headers.length} className="px-5 py-8 text-center text-slate-500">{empty}</td></tr>}</tbody></table></div>; }
