import { useEffect, useMemo, useState } from "react";
import PageMeta from "../../components/common/PageMeta";
import { fetchMyPatientProfile, PatientProfile } from "../../api/patient";

const cdf = (value: string | number) => `${Number(value || 0).toLocaleString("fr-CD")} CDF`;
const dateTime = (value?: string | null) => value ? new Intl.DateTimeFormat("fr-CD", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "—";
const label = (status: string) => ({ PAID: "Payée", PARTIALLY_PAID: "Partiellement payée", PENDING: "Impayée", ISSUED: "À régler", CANCELLED: "Annulée" } as Record<string, string>)[status] || status;

export default function PatientPayments() {
 const [profile, setProfile] = useState<PatientProfile | null>(null); const [error, setError] = useState("");
 useEffect(() => { const load = async () => { try { setProfile(await fetchMyPatientProfile()); setError(""); } catch (cause) { setError(cause instanceof Error ? cause.message : "Impossible de charger vos factures."); } }; void load(); window.addEventListener("d7:invoice.updated", load); window.addEventListener("d7:payment.created", load); return () => { window.removeEventListener("d7:invoice.updated", load); window.removeEventListener("d7:payment.created", load); }; }, []);
 const totalDue = useMemo(() => profile?.invoices?.reduce((sum, invoice) => sum + Math.max(0, Number(invoice.balanceDue)), 0) || 0, [profile]);
 return <div className="space-y-6"><PageMeta title="Paiements | Aulia Care" description="Factures et paiements du patient." /><section className="aulia-card p-5 sm:p-7"><p className="text-xs font-semibold uppercase tracking-wide text-aulia-teal">Facturation sécurisée</p><h1 className="mt-1 text-2xl font-semibold text-slate-900 dark:text-white">Mes paiements et mes factures</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-500 dark:text-slate-400">Les montants sont affichés exclusivement en francs congolais (CDF). Une facture négociée ne peut être appliquée qu’après approbation documentée par la Finance ou l’Administration.</p><div className="mt-5 rounded-2xl bg-aulia-navy p-4 text-white"><p className="text-sm text-white/75">Solde total à régler</p><p className="mt-1 text-3xl font-semibold">{cdf(totalDue)}</p></div></section>{error ? <div className="rounded-2xl border border-rose-300 bg-rose-50 p-4 text-sm text-rose-800 dark:border-rose-900/60 dark:bg-rose-950/40 dark:text-rose-200">{error}</div> : null}
 <section className="aulia-card p-5 sm:p-6"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><h2 className="text-lg font-semibold text-slate-900 dark:text-white">Historique des factures</h2><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">Sélectionnez une facture auprès de la caisse ou depuis le canal de paiement officiel configuré par Aulia Care.</p></div></div><div className="mt-5 overflow-x-auto"><table className="min-w-[760px] w-full text-left text-sm"><thead className="border-b border-slate-200 text-xs uppercase tracking-wide text-slate-500 dark:border-white/10 dark:text-slate-400"><tr><th className="px-3 py-3">Émise le</th><th className="px-3 py-3">Total</th><th className="px-3 py-3">Reste</th><th className="px-3 py-3">État</th><th className="px-3 py-3">Paiements</th><th className="px-3 py-3">Réduction</th></tr></thead><tbody>{profile?.invoices?.length ? profile.invoices.map((invoice, index) => <tr key={invoice.id || index} className="border-b border-slate-100 align-top dark:border-white/10"><td className="px-3 py-4 text-slate-700 dark:text-slate-200">{dateTime(invoice.issuedAt)}</td><td className="px-3 py-4 font-medium text-slate-900 dark:text-white">{cdf(invoice.totalAmount)}</td><td className="px-3 py-4 text-slate-700 dark:text-slate-200">{cdf(invoice.balanceDue)}</td><td className="px-3 py-4"><span className="rounded-full bg-aulia-mist px-2.5 py-1 text-xs font-semibold text-aulia-teal dark:bg-aulia-teal/15">{label(invoice.status)}</span></td><td className="px-3 py-4 text-xs text-slate-500 dark:text-slate-400">{invoice.payments?.length ? invoice.payments.map((payment, paymentIndex) => <p key={paymentIndex}>{cdf(payment.amount)} · {payment.method} · {dateTime(payment.paidAt)}</p>) : "Aucun paiement enregistré"}</td><td className="px-3 py-4 text-xs text-slate-500 dark:text-slate-400">{invoice.discountRequests?.length ? invoice.discountRequests.map((discount, discountIndex) => <p key={discountIndex}>{cdf(discount.amount)} · {discount.status}</p>) : "Aucune"}</td></tr>) : <tr><td colSpan={6} className="px-3 py-8 text-center text-slate-500 dark:text-slate-400">Aucune facture dans votre dossier.</td></tr>}</tbody></table></div></section>
 <section className="rounded-2xl border border-aulia-teal/20 bg-aulia-mist/55 p-5 text-sm leading-6 text-slate-600 dark:bg-aulia-teal/10 dark:text-slate-300"><p className="font-semibold text-slate-900 dark:text-white">Paiement Mobile Money</p><p className="mt-1">Les numéros Orange, Airtel et Vodacom visibles ici doivent venir de la configuration validée par l’administrateur. Aucun numéro ou paiement ne sera simulé par le portail : le paiement sera proposé dès qu’un canal officiel activé est disponible.</p></section></div>;
}
