import { useEffect, useState } from "react";
import PageMeta from "../../components/common/PageMeta";
import { fetchMyPatientProfile, PatientProfile } from "../../api/patient";

const dateTime = (value?: string | null) => value ? new Intl.DateTimeFormat("fr-CD", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "—";
const nameOf = (person?: { displayName?: string | null; firstName?: string | null; lastName?: string | null } | null) => person?.displayName || [person?.firstName, person?.lastName].filter(Boolean).join(" ") || "Non renseigné";

export default function PatientHospitalization() {
 const [profile, setProfile] = useState<PatientProfile | null>(null); const [error, setError] = useState("");
 useEffect(() => { const load = async () => { try { setProfile(await fetchMyPatientProfile()); setError(""); } catch (cause) { setError(cause instanceof Error ? cause.message : "Impossible de charger vos hospitalisations."); } }; void load(); window.addEventListener("d7:hospitalization.updated", load); window.addEventListener("d7:nursing.task.updated", load); return () => { window.removeEventListener("d7:hospitalization.updated", load); window.removeEventListener("d7:nursing.task.updated", load); }; }, []);
 return <div className="space-y-6"><PageMeta title="Hospitalisation | Aulia Care" description="Suivi du séjour hospitalier du patient." /><section className="aulia-card p-5 sm:p-7"><p className="text-xs font-semibold uppercase tracking-wide text-aulia-teal">Mon séjour</p><h1 className="mt-1 text-2xl font-semibold text-slate-900 dark:text-white">Hospitalisations et suivi de soins</h1><p className="mt-2 text-sm leading-6 text-slate-500 dark:text-slate-400">Faites glisser les cartes horizontalement pour consulter vos séjours. Les consignes affichées sont informatives : l’équipe reste votre interlocuteur médical.</p></section>{error ? <div className="rounded-2xl border border-rose-300 bg-rose-50 p-4 text-sm text-rose-800 dark:border-rose-900/60 dark:bg-rose-950/40 dark:text-rose-200">{error}</div> : null}
 <div className="flex snap-x gap-5 overflow-x-auto pb-3">{profile?.hospitalizations?.length ? profile.hospitalizations.map((stay, index) => <article key={stay.id || index} className="aulia-card min-w-[min(100%,38rem)] snap-start p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-semibold text-slate-900 dark:text-white">{stay.ServiceUnit?.name || "Hospitalisation"}</h2><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">Entrée le {dateTime(stay.admittedAt)}</p></div><span className="rounded-full bg-aulia-mist px-3 py-1 text-xs font-semibold text-aulia-teal dark:bg-aulia-teal/15">{stay.dischargedAt ? "Séjour terminé" : "Séjour en cours"}</span></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><Cell label="Motif" value={stay.admissionReason || "Non renseigné"}/><Cell label="Chambre / lit" value={[stay.ServiceUnit?.location, stay.bedNumber && `Lit ${stay.bedNumber}`].filter(Boolean).join(" · ") || "À confirmer"}/><Cell label="Médecin référent" value={nameOf(stay.physician)}/><Cell label="Infirmier·ère référent·e" value={nameOf(stay.nurseInCharge)}/></div>{stay.nurseAssignments?.length ? <div className="mt-5"><p className="text-xs font-semibold uppercase tracking-wide text-slate-500 dark:text-slate-400">Relais infirmiers</p><div className="mt-2 flex flex-wrap gap-2">{stay.nurseAssignments.map((item, assignmentIndex) => <span key={assignmentIndex} className="rounded-full border border-slate-200 px-3 py-1 text-xs text-slate-700 dark:border-white/10 dark:text-slate-200">{item.coverage === "DAY" ? "Jour" : "Nuit"} · {nameOf(item.nurse)}</span>)}</div></div> : null}<TaskList title="Soins planifiés" tasks={stay.nursingCareTasks || []}/><MedicationList items={stay.medicationAdministrations || []}/></article>) : <article className="aulia-card min-w-full p-6 text-sm text-slate-500 dark:text-slate-400">Aucun séjour hospitalier n’est enregistré dans votre dossier.</article>}</div></div>;
}
function Cell({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-aulia-mist/60 p-3 dark:bg-white/5"><p className="text-xs text-slate-500 dark:text-slate-400">{label}</p><p className="mt-1 text-sm font-medium text-slate-800 dark:text-white">{value}</p></div>; }
function TaskList({ title, tasks }: { title: string; tasks: NonNullable<PatientProfile["hospitalizations"]>[number]["nursingCareTasks"] }) { return <div className="mt-5"><h3 className="font-semibold text-slate-900 dark:text-white">{title}</h3>{tasks?.length ? <div className="mt-3 space-y-2">{tasks.map((task, index) => <div key={task.id || index} className="rounded-xl border border-slate-200 p-3 text-sm dark:border-white/10"><div className="flex justify-between gap-3"><p className="font-medium text-slate-800 dark:text-white">{task.title}</p><span className="text-xs text-slate-500 dark:text-slate-400">{task.status}</span></div><p className="mt-1 text-xs text-slate-500 dark:text-slate-400">Prévu : {dateTime(task.dueAt)}{task.assignedNurse ? ` · ${nameOf(task.assignedNurse)}` : ""}</p>{task.instructions ? <p className="mt-2 text-xs text-slate-600 dark:text-slate-300">{task.instructions}</p> : null}</div>)}</div> : <p className="mt-2 text-sm text-slate-500 dark:text-slate-400">Aucun soin planifié visible.</p>}</div>; }
function MedicationList({ items }: { items: NonNullable<PatientProfile["hospitalizations"]>[number]["medicationAdministrations"] }) { return <div className="mt-5"><h3 className="font-semibold text-slate-900 dark:text-white">Administrations de traitement</h3>{items?.length ? <div className="mt-3 space-y-2">{items.map((item, index) => <div key={item.id || index} className="rounded-xl bg-aulia-mist/55 p-3 text-sm dark:bg-white/5"><p className="font-medium text-slate-800 dark:text-white">{item.prescriptionLine?.medication?.name || "Traitement prescrit"}</p><p className="mt-1 text-xs text-slate-500 dark:text-slate-400">{item.status} · prévu le {dateTime(item.scheduledAt)}{item.administeredAt ? ` · réalisé le ${dateTime(item.administeredAt)}` : ""}</p>{item.observation ? <p className="mt-2 text-xs text-slate-600 dark:text-slate-300">{item.observation}</p> : null}</div>)}</div> : <p className="mt-2 text-sm text-slate-500 dark:text-slate-400">Aucune administration enregistrée.</p>}</div>; }
