import { useEffect, useState } from "react";
import PageMeta from "../../components/common/PageMeta";
import { fetchMyPatientProfile, PatientProfile } from "../../api/patient";

const dateTime = (value?: string | null) => value ? new Intl.DateTimeFormat("fr-CD", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "—";
const labStatus = (status: string) => ({ AVAILABLE: "Disponible", SENT: "Disponible", COMPLETED: "Disponible", VERIFIED: "Disponible", CANCELLED: "Annulé" } as Record<string, string>)[status] || "En cours de traitement";

export default function PatientResults() {
  const [profile, setProfile] = useState<PatientProfile | null>(null);
  const [error, setError] = useState("");
  useEffect(() => { const load = async () => { try { setProfile(await fetchMyPatientProfile()); setError(""); } catch (cause) { setError(cause instanceof Error ? cause.message : "Impossible de charger vos résultats."); } }; void load(); window.addEventListener("aulia:lab.result.published", load); window.addEventListener("aulia:imaging.report.published", load); return () => { window.removeEventListener("aulia:lab.result.published", load); window.removeEventListener("aulia:imaging.report.published", load); }; }, []);
  return <div className="space-y-6"><PageMeta title="Examens et résultats | Aulia Care" description="Résultats biologiques et radiologiques validés." />
    <section className="aulia-card p-5 sm:p-7"><p className="text-xs font-semibold uppercase tracking-wide text-aulia-teal">Dossier patient</p><h1 className="mt-1 text-2xl font-semibold text-slate-900 dark:text-white">Mes examens et résultats</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-500 dark:text-slate-400">Un résultat apparaît ici uniquement lorsque le laboratoire ou la radiologie l’a rendu disponible dans votre dossier. Pour toute interprétation médicale, contactez votre soignant.</p></section>
    {error ? <div className="rounded-2xl border border-rose-300 bg-rose-50 p-4 text-sm text-rose-800 dark:border-rose-900/60 dark:bg-rose-950/40 dark:text-rose-200">{error}</div> : null}
    <section className="grid gap-5 xl:grid-cols-2"><ResultGroup title="Laboratoire" empty="Aucun examen de laboratoire visible dans votre dossier." items={profile?.labRequests?.map((request) => <article key={request.id || request.requestedAt} className="rounded-2xl border border-slate-200 p-4 dark:border-white/10"><div className="flex flex-wrap items-start justify-between gap-2"><div><h3 className="font-semibold text-slate-900 dark:text-white">{request.specimenType || "Examen de laboratoire"}</h3><p className="mt-1 text-xs text-slate-500 dark:text-slate-400">Demandé le {dateTime(request.requestedAt)}</p></div><span className="rounded-full bg-aulia-mist px-2.5 py-1 text-xs font-semibold text-aulia-teal dark:bg-aulia-teal/15">{labStatus(request.status)}</span></div>{request.results?.length ? <div className="mt-4 overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="text-xs text-slate-500 dark:text-slate-400"><tr><th className="pb-2 pr-3">Paramètre</th><th className="pb-2 pr-3">Résultat</th><th className="pb-2">Référence / commentaire</th></tr></thead><tbody>{request.results.flatMap((result) => result.parameters?.length ? result.parameters.map((parameter, index) => <tr key={`${result.resultName}-${index}`} className="border-t border-slate-100 dark:border-white/10"><td className="py-2 pr-3 font-medium text-slate-800 dark:text-white">{parameter.labTestParameter?.name || result.resultName}</td><td className="py-2 pr-3 text-slate-700 dark:text-slate-200">{parameter.valueNumeric ?? parameter.valueText ?? "—"} {parameter.labTestParameter?.unit || result.units || ""}</td><td className="py-2 text-slate-500 dark:text-slate-400">{parameter.labTestParameter?.referenceRange || parameter.interpretation || result.interpretation || "—"}</td></tr>) : <tr key={result.resultName} className="border-t border-slate-100 dark:border-white/10"><td className="py-2 pr-3 font-medium text-slate-800 dark:text-white">{result.resultName}</td><td className="py-2 pr-3 text-slate-700 dark:text-slate-200">{result.resultValue || "—"} {result.units || ""}</td><td className="py-2 text-slate-500 dark:text-slate-400">{result.interpretation || "—"}</td></tr>)}</tbody></table></div> : <p className="mt-3 text-sm text-slate-500 dark:text-slate-400">Les résultats ne sont pas encore disponibles.</p>}</article>)} />
      <ResultGroup title="Radiologie et imagerie" empty="Aucun examen radiologique visible dans votre dossier." items={profile?.imagingRequests?.map((request) => <article key={`${request.modality}-${request.createdAt}`} className="rounded-2xl border border-slate-200 p-4 dark:border-white/10"><div className="flex flex-wrap items-start justify-between gap-2"><div><h3 className="font-semibold text-slate-900 dark:text-white">{request.modality} · {request.bodyPart}</h3><p className="mt-1 text-xs text-slate-500 dark:text-slate-400">Demandé le {dateTime(request.createdAt)}</p></div><span className="rounded-full bg-aulia-mist px-2.5 py-1 text-xs font-semibold text-aulia-teal dark:bg-aulia-teal/15">{request.report?.impression ? "Compte-rendu disponible" : "En cours"}</span></div>{request.report?.impression ? <div className="mt-4 rounded-xl bg-aulia-mist/55 p-3 text-sm leading-6 text-slate-700 dark:bg-white/5 dark:text-slate-200"><p className="text-xs font-semibold uppercase tracking-wide text-slate-500 dark:text-slate-400">Conclusion validée</p><p className="mt-1">{request.report.impression}</p></div> : <p className="mt-3 text-sm text-slate-500 dark:text-slate-400">Le compte-rendu n’est pas encore disponible.</p>}</article>)} />
    </section></div>;
}
function ResultGroup({ title, empty, items }: { title: string; empty: string; items?: React.ReactNode[] }) { return <section className="aulia-card p-5 sm:p-6"><h2 className="text-lg font-semibold text-slate-900 dark:text-white">{title}</h2><div className="mt-4 space-y-4">{items?.length ? items : <p className="rounded-xl border border-dashed border-slate-300 p-4 text-sm text-slate-500 dark:border-white/15 dark:text-slate-400">{empty}</p>}</div></section>; }
