import { FormEvent, ReactNode, useCallback, useEffect, useMemo, useState } from "react";
import PageBreadcrumb from "../../components/common/PageBreadCrumb";
import PageMeta from "../../components/common/PageMeta";
import { ClientPagination, useClientPagination } from "../../components/common/ClientPagination";
import { createBankAccount, fetchFinanceBanking, fetchFinanceTreasury, FinanceBanking, FinanceTreasury, importBankStatementEntry, updateBankAccountStatus } from "../../api/finance";
import { useRealtime } from "../../context/RealtimeContext";

const cdf = (value: number) => new Intl.NumberFormat("fr-CD", { style: "currency", currency: "CDF", maximumFractionDigits: 0 }).format(Number(value || 0));
const date = (value?: string | null) => value ? new Date(value).toLocaleDateString("fr-FR") : "Non renseignée";
const labels: Record<string, string> = { PENDING_APPROVAL: "En attente de validation", ACTIVE: "Actif", SUSPENDED: "Suspendu", CLOSED: "Clôturé" };
const field = "mt-1 w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm text-slate-900 outline-none focus:border-aulia-teal dark:border-slate-700 dark:bg-slate-950 dark:text-white";

function Modal({ title, children, close }: { title: string; children: ReactNode; close: () => void }) {
  return <div role="dialog" aria-modal="true" className="fixed inset-0 z-[100000] grid place-items-center bg-slate-950/60 p-3" onMouseDown={close}>
    <section className="max-h-[calc(100dvh-1.5rem)] w-full max-w-lg overflow-y-auto rounded-3xl border border-slate-200 bg-white p-5 shadow-2xl dark:border-slate-700 dark:bg-slate-900" onMouseDown={(event) => event.stopPropagation()}>
      <div className="flex items-start justify-between gap-4"><h2 className="text-lg font-bold text-slate-900 dark:text-white">{title}</h2><button type="button" onClick={close} className="rounded-lg px-2 py-1 text-slate-500 hover:bg-slate-100 dark:hover:bg-slate-800" aria-label="Fermer">×</button></div><div className="mt-5">{children}</div>
    </section>
  </div>;
}

export default function TresorerieFinance() {
  const { socket } = useRealtime();
  const [data, setData] = useState<FinanceTreasury | null>(null);
  const [banking, setBanking] = useState<FinanceBanking | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState<string | null>(null);
  const [query, setQuery] = useState("");
  const [modal, setModal] = useState<"bank" | "statement" | "confirm" | null>(null);
  const [accountId, setAccountId] = useState<string | null>(null);
  const [saving, setSaving] = useState(false);
  const load = useCallback(async () => { try { setError(null); const [treasury, accounts] = await Promise.all([fetchFinanceTreasury(), fetchFinanceBanking()]); setData(treasury); setBanking(accounts); } catch (reason) { setError(reason instanceof Error ? reason.message : "Impossible de charger la trésorerie."); } }, []);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { const refresh = () => void load(); socket?.on("finance.updated", refresh); return () => socket?.off("finance.updated", refresh); }, [socket, load]);
  const receivables = useMemo(() => (data?.receivables || []).filter((item) => `${item.debtor} ${item.invoiceType}`.toLowerCase().includes(query.trim().toLowerCase())), [data, query]);
  const receivablePages = useClientPagination(receivables, 10);
  const supplierPages = useClientPagination(data?.supplierInvoices || [], 10);
  const payrollPages = useClientPagination(data?.payroll || [], 10);
  const bankPages = useClientPagination(banking?.accounts || [], 5);

  const createAccount = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); try { setSaving(true); const result = await createBankAccount({ bankName: String(form.get("bankName") || ""), accountName: String(form.get("accountName") || ""), accountNumber: String(form.get("accountNumber") || ""), currency: "CDF", openingBalance: Number(form.get("openingBalance") || 0), openingBalanceAt: String(form.get("openingBalanceAt") || "") || undefined }); setModal(null); setSuccess(`Compte ${result.maskedAccountNumber} enregistré. Un administrateur différent doit maintenant l’activer.`); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Création du compte bancaire impossible."); } finally { setSaving(false); } };
  const addStatement = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!accountId) return; const form = new FormData(event.currentTarget); try { setSaving(true); await importBankStatementEntry(accountId, { externalReference: String(form.get("reference") || ""), transactionAt: String(form.get("transactionAt") || ""), amount: Number(form.get("amount")), description: String(form.get("description") || "") }); setModal(null); setAccountId(null); setSuccess("Ligne de relevé importée. Elle est maintenant à rapprocher puis à faire valider."); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Import de relevé impossible."); } finally { setSaving(false); } };
  const activateAccount = async () => { if (!accountId) return; try { setSaving(true); await updateBankAccountStatus(accountId, "ACTIVE"); setModal(null); setAccountId(null); setSuccess("Compte bancaire activé et tracé avec succès."); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Activation impossible. Un administrateur différent du créateur doit valider l’action."); } finally { setSaving(false); } };

  return <main className="mx-auto w-full max-w-[1540px] space-y-5 px-3 pb-8 pt-2 sm:px-5 lg:px-7">
    <PageMeta title="Trésorerie | Aulia Care" description="Créances, banque, fournisseurs et paie" /><PageBreadcrumb pageTitle="Trésorerie & opérations" />
    <section className="rounded-3xl border border-aulia-teal/30 bg-gradient-to-r from-slate-950 to-aulia-teal px-5 py-6 text-white"><p className="text-sm text-teal-100">Direction financière</p><h1 className="mt-1 text-2xl font-bold">Trésorerie, créances & engagements</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-100">Les comptes bancaires sont chiffrés et masqués à l’écran. Leur activation, ainsi que les rapprochements, nécessitent une validation séparée.</p></section>
    {error ? <div role="alert" className="rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-800 dark:border-rose-900 dark:bg-rose-950/30 dark:text-rose-200">{error}<button onClick={() => { setError(null); void load(); }} className="ml-3 rounded-lg bg-rose-700 px-3 py-1 font-semibold text-white">Réessayer</button></div> : null}
    {success ? <div role="status" className="rounded-2xl border border-aulia-teal/30 bg-aulia-teal/10 p-4 text-sm text-aulia-navy dark:text-teal-100">{success}<button onClick={() => setSuccess(null)} className="ml-3 rounded-lg bg-aulia-teal px-3 py-1 font-semibold text-white">Fermer</button></div> : null}
    {!data && !error ? <div className="rounded-2xl border border-slate-200 bg-white p-8 text-sm text-slate-500 dark:border-slate-800 dark:bg-slate-900">Chargement de la trésorerie…</div> : null}
    {data ? <>
      <section className="grid gap-4 md:grid-cols-4">{data.agedReceivables.map((item) => <article key={item.bucket} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-800 dark:bg-slate-900"><p className="text-sm text-slate-500">Créances {item.bucket}</p><p className="mt-2 text-xl font-bold text-slate-900 dark:text-white">{cdf(item.amount)}</p><p className="mt-1 text-xs text-slate-500">{item.count} dossier(s)</p></article>)}</section>
      <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-semibold text-slate-900 dark:text-white">Banques & rapprochements</h2><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">Lier, valider et rapprocher les comptes de l’établissement.</p></div><button onClick={() => setModal("bank")} className="rounded-xl bg-aulia-teal px-4 py-2.5 text-sm font-semibold text-white">Lier un compte bancaire</button></div><div className="mt-5 grid gap-3 lg:grid-cols-2">{bankPages.pageItems.length ? bankPages.pageItems.map((account) => <article key={account.id} className="rounded-2xl border border-slate-200 p-4 dark:border-slate-700"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-semibold text-slate-900 dark:text-white">{account.bankName}</p><p className="text-sm text-slate-500">{account.accountName} · {account.maskedAccountNumber}</p></div><span className={`rounded-full px-2 py-1 text-xs font-semibold ${account.status === "ACTIVE" ? "bg-aulia-teal/15 text-aulia-teal" : "bg-amber-100 text-amber-800 dark:bg-amber-950 dark:text-amber-200"}`}>{labels[account.status]}</span></div><p className="mt-3 text-sm text-slate-600 dark:text-slate-300">Solde d’ouverture : <strong>{cdf(account.openingBalance)}</strong> · {account.pendingStatementCount} ligne(s) à rapprocher</p><div className="mt-4 flex flex-wrap gap-2">{account.status === "PENDING_APPROVAL" ? <button onClick={() => { setAccountId(account.id); setModal("confirm"); }} className="rounded-lg border border-aulia-teal/40 px-3 py-1.5 text-xs font-semibold text-aulia-teal">Activer après contrôle</button> : null}{account.status === "ACTIVE" ? <button onClick={() => { setAccountId(account.id); setModal("statement"); }} className="rounded-lg border border-slate-300 px-3 py-1.5 text-xs font-semibold text-slate-700 dark:border-slate-700 dark:text-slate-200">Importer une ligne de relevé</button> : null}</div></article>) : <p className="rounded-2xl bg-slate-50 p-4 text-sm text-slate-500 dark:bg-slate-800">Aucun compte lié. Ajoutez seulement les comptes dont l’établissement est titulaire.</p>}</div><ClientPagination page={bankPages.page} totalPages={bankPages.totalPages} totalItems={banking?.accounts.length || 0} pageSize={5} onPageChange={bankPages.setPage} label="comptes bancaires" /><p className="mt-3 text-xs text-slate-500">L’import d’une ligne de relevé ne crée aucun paiement. Elle doit être rapprochée puis approuvée par une seconde personne.</p></section>
      <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="font-semibold text-slate-900 dark:text-white">Portefeuille assurances, entreprises & patients</h2><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">Balance âgée des montants restants à recouvrer.</p></div><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Rechercher un débiteur ou un type…" className="w-full rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm text-slate-900 outline-none focus:border-aulia-teal sm:max-w-xs dark:border-slate-700 dark:bg-slate-950 dark:text-white" /></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-b border-slate-200 text-xs uppercase tracking-wide text-slate-500 dark:border-slate-700"><tr><th className="p-3">Débiteur</th><th className="p-3">Type</th><th className="p-3">Émission</th><th className="p-3">Retard</th><th className="p-3 text-right">À recouvrer</th></tr></thead><tbody>{receivablePages.pageItems.length ? receivablePages.pageItems.map((item) => <tr key={item.id} className="border-b border-slate-100 dark:border-slate-800"><td className="p-3 font-medium text-slate-900 dark:text-white">{item.debtor}</td><td className="p-3 text-slate-600 dark:text-slate-300">{item.invoiceType}</td><td className="p-3 text-slate-600 dark:text-slate-300">{date(item.issuedAt)}</td><td className="p-3">{item.ageDays} j</td><td className="p-3 text-right font-semibold text-slate-900 dark:text-white">{cdf(item.amount)}</td></tr>) : <tr><td className="p-5 text-center text-slate-500" colSpan={5}>Aucune créance ne correspond à la recherche.</td></tr>}</tbody></table></div><ClientPagination page={receivablePages.page} totalPages={receivablePages.totalPages} totalItems={receivables.length} pageSize={10} onPageChange={receivablePages.setPage} label="créances" /><p className="mt-3 text-xs text-slate-500">{data.reminderNotice}</p></section>
      <section className="grid gap-5 xl:grid-cols-2"><article className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 className="font-semibold text-slate-900 dark:text-white">Fournisseurs & échéances</h2><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[640px] text-left text-sm"><thead className="border-b border-slate-200 text-xs uppercase text-slate-500 dark:border-slate-700"><tr><th className="p-3">Fournisseur</th><th className="p-3">Échéance</th><th className="p-3 text-right">Solde</th></tr></thead><tbody>{supplierPages.pageItems.length ? supplierPages.pageItems.map((item) => <tr key={item.id} className="border-b border-slate-100 dark:border-slate-800"><td className="p-3"><p className="font-medium text-slate-900 dark:text-white">{item.supplier}</p><p className="text-xs text-slate-500">{item.invoiceNumber}</p></td><td className="p-3 text-slate-600 dark:text-slate-300">{date(item.dueDate)}</td><td className="p-3 text-right font-semibold text-slate-900 dark:text-white">{cdf(item.balanceDue)}</td></tr>) : <tr><td className="p-5 text-center text-slate-500" colSpan={3}>Aucune facture fournisseur impayée.</td></tr>}</tbody></table></div><ClientPagination page={supplierPages.page} totalPages={supplierPages.totalPages} totalItems={data.supplierInvoices.length} pageSize={10} onPageChange={supplierPages.setPage} label="factures fournisseurs" /></article><article className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h2 className="font-semibold text-slate-900 dark:text-white">Masse salariale & paie</h2><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[640px] text-left text-sm"><thead className="border-b border-slate-200 text-xs uppercase text-slate-500 dark:border-slate-700"><tr><th className="p-3">Employé</th><th className="p-3">Statut</th><th className="p-3 text-right">Net</th></tr></thead><tbody>{payrollPages.pageItems.length ? payrollPages.pageItems.map((item) => <tr key={item.id} className="border-b border-slate-100 dark:border-slate-800"><td className="p-3"><p className="font-medium text-slate-900 dark:text-white">{item.employee}</p><p className="text-xs text-slate-500">{item.department} · période terminée le {date(item.periodEnd)}</p></td><td className="p-3">{item.status}</td><td className="p-3 text-right font-semibold text-slate-900 dark:text-white">{cdf(item.netAmount)}</td></tr>) : <tr><td className="p-5 text-center text-slate-500" colSpan={3}>Aucune paie enregistrée.</td></tr>}</tbody></table></div><ClientPagination page={payrollPages.page} totalPages={payrollPages.totalPages} totalItems={data.payroll.length} pageSize={10} onPageChange={payrollPages.setPage} label="paies" /></article></section>
    </> : null}
    {modal === "bank" ? <Modal title="Lier un compte bancaire" close={() => setModal(null)}><form onSubmit={createAccount} className="space-y-4"><p className="rounded-xl bg-aulia-teal/10 p-3 text-sm text-aulia-navy dark:text-teal-100">Le numéro est chiffré côté serveur et ne sera plus affiché qu’en quatre derniers caractères. Le compte reste inactif jusqu’à la validation d’un administrateur distinct.</p><label className="block text-sm font-medium text-slate-700 dark:text-slate-200">Banque<input required name="bankName" className={field} /></label><label className="block text-sm font-medium text-slate-700 dark:text-slate-200">Intitulé du compte<input required name="accountName" className={field} /></label><label className="block text-sm font-medium text-slate-700 dark:text-slate-200">Numéro de compte / IBAN<input required name="accountNumber" autoComplete="off" className={field} /></label><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium text-slate-700 dark:text-slate-200">Solde d’ouverture CDF<input name="openingBalance" type="number" defaultValue="0" className={field} /></label><label className="text-sm font-medium text-slate-700 dark:text-slate-200">Date du solde<input name="openingBalanceAt" type="date" className={field} /></label></div><button disabled={saving} className="w-full rounded-xl bg-aulia-teal px-4 py-3 font-semibold text-white disabled:opacity-50">{saving ? "Enregistrement…" : "Enregistrer pour validation"}</button></form></Modal> : null}
    {modal === "statement" ? <Modal title="Importer une ligne de relevé" close={() => { setModal(null); setAccountId(null); }}><form onSubmit={addStatement} className="space-y-4"><p className="rounded-xl bg-amber-50 p-3 text-sm text-amber-900 dark:bg-amber-950/30 dark:text-amber-100">Utilisez la référence exacte du relevé. Cette action ne crée ni paiement ni encaissement : elle prépare le rapprochement contrôlé.</p><label className="block text-sm font-medium text-slate-700 dark:text-slate-200">Référence bancaire<input required name="reference" className={field} /></label><label className="block text-sm font-medium text-slate-700 dark:text-slate-200">Date de l’opération<input required name="transactionAt" type="datetime-local" className={field} /></label><label className="block text-sm font-medium text-slate-700 dark:text-slate-200">Montant CDF<input required name="amount" type="number" step="0.01" className={field} /><span className="mt-1 block text-xs text-slate-500">Entrée positive, sortie négative.</span></label><label className="block text-sm font-medium text-slate-700 dark:text-slate-200">Libellé<textarea required name="description" className={field} rows={3} /></label><button disabled={saving} className="w-full rounded-xl bg-aulia-teal px-4 py-3 font-semibold text-white disabled:opacity-50">{saving ? "Import…" : "Importer la ligne"}</button></form></Modal> : null}
    {modal === "confirm" ? <Modal title="Activer ce compte bancaire ?" close={() => { setModal(null); setAccountId(null); }}><p className="text-sm leading-6 text-slate-600 dark:text-slate-300">Confirmez uniquement après avoir vérifié la banque, l’intitulé et les quatre derniers chiffres avec le relevé officiel. Cette action est auditée et exige une personne différente du créateur.</p><div className="mt-6 flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><button onClick={() => { setModal(null); setAccountId(null); }} className="rounded-xl border border-slate-300 px-4 py-2.5 font-semibold text-slate-700 dark:border-slate-700 dark:text-slate-200">Annuler</button><button disabled={saving} onClick={() => void activateAccount()} className="rounded-xl bg-aulia-teal px-4 py-2.5 font-semibold text-white disabled:opacity-50">Confirmer l’activation</button></div></Modal> : null}
  </main>;
}
